
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xkrtvsqprwdeueevouzw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhrcnR2c3FwcndkZXVlZXZvdXp3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMxNTEzNjksImV4cCI6MjA1ODcyNzM2OX0.B65gCranE11BqkD_nlBfy-yupik3oNNIREysqY6kN9k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    persistSession: true,
    autoRefreshToken: true,
    storageKey: 'qr-attendance-storage-key',
    debug: true // This helps with debugging authentication issues
  },
  global: {
    headers: {
      'Content-Type': 'application/json'
    }
  },
  db: {
    schema: 'public'
  }
});

// Error handling utility for Supabase operations
export const handleSupabaseError = (error: unknown, fallbackMessage: string = "Operation failed"): string => {
  console.error("Supabase error:", error);
  
  if (error instanceof Error) {
    // Return a user-friendly error message
    if (error.message.includes("network")) {
      return "Network error. Please check your connection.";
    } else if (error.message.includes("not found") || error.message.includes("404")) {
      return "The requested resource was not found.";
    } else if (error.message.includes("permission") || error.message.includes("403")) {
      return "You don't have permission for this operation.";
    } else if (error.message.length < 100) { // Only return original message if it's short/readable
      return error.message;
    }
  }
  
  return fallbackMessage;
};
